# Site settings
# can be referred by {{ site.description }}
title: Runrioter's blog
email: runrioter@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Runrioter's blog which is a journal about programming
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://runrioter.github.com" # the base hostname & protocol for your site
#twitter_username: Runrioter
github_username:  Runrioter

# Build settings
markdown: kramdown
