# global configuration
source: .
exclude:
  - README.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - vendor
  - node_modules
  - Makefile
  - package.json

destination: ./_site
plugins_dir: ./_plugins
layouts_dir: ./_layouts
data_dir: ./_data
includes_dir: ./_includes

timezone: Asia/Shanghai
encoding: "utf-8"

strict_front_matter: true

sass:
  sass_dir: _sass
  style: compressed

# publish posts in future date
#future: true

# produce an index for related posts
#lsi: true

# limit the number of posts to parse and publish
limit_posts: 50
excerpt_separator: "\n\n"

show_drafts: true

# Site settings
# For example: can be referred by {{ site.title }}
title: Runrioter's Journal

email: runrioter@gmail.com
# this means to ignore newlines until "baseurl:"
description: Journals On Programming.
baseurl: "" # the subpath of your site, e.g. /blog/

url: "https://www.megorich.com" # the base hostname & protocol for your site

# twitter_username: Runrioter
github_username:  Runrioter

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  auto_ids: true
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  input: GFM
  hard_wrap: false
  footnote_nr: 1
  show_warnings: true
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    # css_class: 'highlight'
    # line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      #line_numbers: true
      #start_line: 1 

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  posts:
    output: true
  authors:
    output: true

# YAML Front Matter defaults
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
      author: "Runrioter"
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
