# global configuration
source: .
exclude: [README.md, CNAME, Gemfile, Gemfile.lock, vendor]
destination: ./_site
plugins_dir: ./_plugins
layouts_dir: ./_layouts
data_dir: ./_data
includes_dir: ./_includes
#collections: null
timezone: Asia/Shanghai
encoding: "utf-8"

# publish posts in future date
#future: true

# produce an index for related posts
#lsi: true

# limit the number of posts to parse and publish
limit_posts: 50

show_drafts: true
# Site settings
# can be referred by {{ site.description }}
title: Runrioter's Journal

email: runrioter@gmail.com
# this means to ignore newlines until "baseurl:"
description: >
  Journals On Programming.
baseurl: "" # the subpath of your site, e.g. /blog/

url: "http://www.megorich.com" # the base hostname & protocol for your site

# twitter_username: Runrioter
github_username:  Runrioter

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      #line_numbers: true
      #start_line: 1 

excerpt_separator: "\n\n"

# YAML Front Matter defaults
defaults:
  - 
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
      author: "Runrioter Wung"
  - 
    scope:
      path: "_drafts"
    values:
      layout: "post"
      author: "Swear Wang"
